WUO

diff --git a/.github/workflows/colcon_in_container.yaml b/.github/workflows/colcon_in_container.yaml
--- a/.github/workflows/colcon_in_container.yaml
+++ b/.github/workflows/colcon_in_container.yaml
@@ -43,10 +43,10 @@ jobs:
         run: |
           sudo apt update
           sudo apt upgrade -y
-          sudo rm /usr/lib/python3.*/EXTERNALLY-MANAGED || true
-          python3 -m pip install --upgrade pip
-          pip install setuptools
-          pip install colcon-common-extensions
+          #          sudo rm /usr/lib/python3.*/EXTERNALLY-MANAGED || true
+          #          python3 -m pip install --upgrade pip
+          #          pip install setuptools
+          #          pip install colcon-common-extensions
           #      - name: Install the extension
           #        run: |
           #          pip install .
@@ -86,38 +86,38 @@ jobs:
           #          ls release_in_container/COLCON_IGNORE
           #          ls release_in_container/demo_nodes_cpp/debian
 
-  eol_distro_in_container_integration_test:
-    name: "EoL distro Integration Test"
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-24.04, [self-hosted, linux, X64, jammy, xlarge]]
-        ros_version: [foxy]
-        provider: [lxd, multipass]
-        exclude:
-          - os: ubuntu-24.04
-            provider: multipass
-          - {os: [self-hosted, linux, X64, jammy, xlarge], provider: lxd}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@v3
-      - uses: actions/setup-python@v5
-      - name: Install LXD
-        if: ${{ matrix.provider == 'lxd' }}
-        uses: canonical/setup-lxd@v0.1.0
-      - name: Install Multipass
-        run: |
-          sudo snap install multipass
-        if: "${{ matrix.provider == 'multipass' }}"
-      - name: Install dependencies
-        run: |
-          sudo apt update
-          sudo apt upgrade -y
-          sudo rm /usr/lib/python3.*/EXTERNALLY-MANAGED || true
-          python3 -m pip install --upgrade pip
-          pip install setuptools
-          pip install colcon-common-extensions
+          #  eol_distro_in_container_integration_test:
+          #    name: "EoL distro Integration Test"
+          #    strategy:
+          #      fail-fast: false
+          #      matrix:
+          #        os: [ubuntu-24.04, [self-hosted, linux, X64, jammy, xlarge]]
+          #        ros_version: [foxy]
+          #        provider: [lxd, multipass]
+          #        exclude:
+          #          - os: ubuntu-24.04
+          #            provider: multipass
+          #          - {os: [self-hosted, linux, X64, jammy, xlarge], provider: lxd}
+          #    runs-on: ${{ matrix.os }}
+          #    steps:
+          #      - name: Checkout sources
+          #        uses: actions/checkout@v3
+          #      - uses: actions/setup-python@v5
+          #      - name: Install LXD
+          #        if: ${{ matrix.provider == 'lxd' }}
+          #        uses: canonical/setup-lxd@v0.1.0
+          #      - name: Install Multipass
+          #        run: |
+          #          sudo snap install multipass
+          #        if: "${{ matrix.provider == 'multipass' }}"
+          #      - name: Install dependencies
+          #        run: |
+          #          sudo apt update
+          #          sudo apt upgrade -y
+          #          sudo rm /usr/lib/python3.*/EXTERNALLY-MANAGED || true
+          #          python3 -m pip install --upgrade pip
+          #          pip install setuptools
+          #          pip install colcon-common-extensions
           #      - name: Install the extension
           #        run: |
           #          pip install .
